export enum RequestStatus {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum RequestType {
  CONSULTATION = 'CONSULTATION',
  MORTGAGE = 'MORTGAGE',
  CALLBACK = 'CALLBACK',
  SELECTION = 'SELECTION',
  CONTACT = 'CONTACT',
}
